// See https://aka.ms/new-console-template for more information
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


Console.WriteLine("Crude App 0001");
Console.Beep(frequency:100,duration: 6);
Console.Beep(frequency:80, duration: 200);
Console.Beep(frequency :45, duration: 45);
Console.Beep(frequency: 100, duration: 6);
Console.Beep(frequency: 80, duration: 2200);
Console.Beep(frequency: 390, duration: 45);
Console.Beep(frequency: 100, duration: 6);
Console.Beep(frequency: 80, duration: 20);
Console.Beep(frequency: 345, duration: 45);
Console.Beep(frequency: 100, duration: 6);
Console.Beep(frequency: 80, duration: 459);
Console.Beep(frequency: 345, duration: 455);
Console.Beep(frequency: 100, duration: 6);
Console.Beep(frequency: 80, duration: 2040);
Console.Beep(frequency: 345, duration: 4534);
Console.Beep(frequency: 1040, duration: 9);
Console.Beep(frequency: 840, duration: 200);
Console.Beep(frequency: 345, duration: 450);
Console.Beep(frequency: 140, duration: 69);
Console.Beep(frequency: 840, duration: 220);
Console.Beep(frequency: 345, duration: 5);
Console.Beep(frequency: 100, duration: 6);
Console.Beep(frequency: 80, duration: 200);
Console.Beep(frequency: 345, duration: 45);
Console.Beep(frequency: 100, duration: 6);
Console.Beep(frequency: 80, duration: 2200);
Console.Beep(frequency: 345, duration: 465);
Console.Beep(frequency: 100, duration: 63);
Console.Beep(frequency: 80, duration: 2200);
Console.Beep(frequency: 345, duration: 45);
Console.Beep(frequency: 100, duration: 6);
Console.Beep(frequency: 80, duration: 2200);
Console.Beep(frequency: 38, duration: 45);
Console.Beep(frequency: 100, duration: 6);
Console.Beep(frequency: 80, duration: 2200);
Console.Beep(frequency: 345, duration: 45);
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();
Console.Beep();